### ISSUE TITLE
[Feature Request] Add Guild Methods

### ISSUE THREAD

**Issue by seailz** [discord-jar/discord.jar#20]
### General Troubleshooting

- [X] You've have checked for similar feature requests.
- [X] You've updated to the latest version of the API.
- [X] You've have checked the PR's for features relating to your suggestion.

### Feature Request Description

https://discord.com/developers/docs/resources/guild#create-guild

**Comment by Blueysh** [comment]
I could claim this

**Comment by seailz** [comment]
> I could claim this

If you want

**Comment by Blueysh** [comment]
would you like me to work on this in the `DiscordJv` class?

**Comment by seailz** [comment]
> would you like me to work on this in the `DiscordJv` class?

wdym?

**Comment by Blueysh** [comment]
> > would you like me to work on this in the `DiscordJv` class?
> 
> 
> 
> wdym?

i meant like adding the methods to the discord jv class

**Comment by seailz** [comment]
> > > would you like me to work on this in the `DiscordJv` class?
> > 
> > 
> > 
> > wdym?
> 
> i meant like adding the methods to the discord jv class

Create Guild is just the start of the methods, this issue is intended for all methods like patch guild, delete guild, etc.

**Comment by Blueysh** [comment]
now that i know i'll keep it in mind 😂

**Comment by Blueysh** [comment]
@seailz was this already done you said?

**Comment by seailz** [comment]
> @seailz was this already done you said?

Only a couple of methods, not all of them.
