### ISSUE TITLE
Why use spring

### ISSUE THREAD

**Issue by DRSchlaubi** [discord-jar/discord.jar#218]
### General Troubleshooting

- [X] You've have checked for similar feature requests.
- [X] You've updated to the latest version of the API.
- [X] You've have checked the PR's for features relating to your suggestion.

### Feature Request Description

I was looking through this library and saw that it is using both okhttp and spring, because spring seems to be kind of a large and overkill library for this, I wonder why that is, since OkHttp [supports websockets too](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-web-socket/)

Also using both gson and org.json seems kinda overkill

**Comment by seailz** [comment]
These are indeed things I'd like to work on. Honestly, I wasn't aware that OkHttp uses websockets, and it's likely something I'll look into after this library is completed in implementing the API.

As for JSON, there was one niche usecase (I can't remember exactly where), where we needed to use GSON to implement some code that org.json couldn't handle. By that time, org.json had already been used as a major part of the lib and it would of been a hell of a lot of work and introduced a ton of bugs if we were to change it.

I'll put this issue on pause for now as we have other priorities to get to, but yeah, these are things I want to sort at some point.
