### ISSUE TITLE
[Feature Request] Compression

### ISSUE THREAD

**Issue by DRSchlaubi** [discord-jar/discord.jar#219]
### General Troubleshooting

- [X] You've have checked for similar feature requests.
- [X] You've updated to the latest version of the API.
- [X] You've have checked the PR's for features relating to your suggestion.

### Feature Request Description

Add support for [Transport Compression](https://discord.com/developers/docs/topics/gateway#transport-compression)

**Comment by seailz** [comment]
That's funny, actually put this in my to-do list just yesterday haha.
